name: "Submit OSBE YouTube Shorts Remover to Web Store"

on:
  workflow_dispatch:

concurrency:
  group: submit-youtube-shorts-remover
  cancel-in-progress: false

jobs:
  submit:
    uses: ./.github/workflows/_submit-extension.yml
    with:
      cancel_pending_submission: true
      extension: youtube-shorts-remover
    secrets:
      submit_keys: ${{ secrets.SUBMIT_KEYS }}
